defaults:
  - override model: cnn
  - override dataset: deepflybrain

# Training settings
train:
  batch_size: 256
  lr: 5e-4
  epochs: 220
  warmup: 500
  clip_grad: true
  save_dir: "/home/hmuhammad/flow/data"
  plot_dir: "/home/hmuhammad/flow/plots"

# General settings
device: "cuda:0"
seed: 42
epsilon: 1e-3
