defaults:
  - model: cnn
  - dataset: deepflybrain

# Training settings
train:
  batch_size: 2048
  lr: 5e-4
  epochs: 950
  warmup: 500
  clip_grad: true
  save_dir: "/home/hmuhammad/flow/data"
  plot_dir: "/home/hmuhammad/flow/plots"

# General settings
device: "cuda:0"
seed: 42
epsilon: 1e-3
