deepflybrain:
  name: "DeepFlyBrain"
  path: "/home/hmuhammad/flow/data/DeepFlyBrain_data.pkl"
  num_classes: 81
  seq_length: 500

deepmel2:
  name: "DeepMEL2"
  path: "/home/hmuhammad/flow/data/DeepMEL2_data.pkl"
  num_classes: 47
  seq_length: 500
